// ============================================================================
// SPI TARGET + ECHO + LED CONTROL
// ============================================================================
//
// Target platform : Shrike Lite FPGA
// Intended flow   : Go Configure compiler
//
// Description:
//   This is a completely self-contained SPI target design.
//   There are NO submodule instantiations.
//
//   The design performs three main functions:
//
//   1. SPI RECEIVE
//      - Receives 8-bit data from an external SPI controller/MCU.
//      - SPI Mode 0 is used:
//          CPOL = 0
//          CPHA = 0
//      - MSB is transmitted/received first.
//
//   2. SPI ECHO
//      - Whenever one complete byte is received,
//        the received byte is loaded into tx_data_reg.
//      - This byte is subsequently returned to the SPI controller
//        through MISO.
//
//   3. LED CONTROL
//      - Receiving 0xAB turns the LED ON.
//      - Receiving 0xFF turns the LED OFF.
//      - Other received values do not change the LED state.
//
// ============================================================================

(* top *) module top (

    // ------------------------------------------------------------------------
    // System clock
    // ------------------------------------------------------------------------
    // 50 MHz system clock.
    //
    // All internal sequential logic operates in this clock domain.
    // The external SPI signals are synchronized into this clock domain.
    // ------------------------------------------------------------------------
    (* iopad_external_pin *) input clk,

    // Clock enable output.
    // Kept permanently HIGH for the external FPGA configuration/interface.
    // ------------------------------------------------------------------------
    (* iopad_external_pin *) output clk_en,

    // ------------------------------------------------------------------------
    // System reset
    // ------------------------------------------------------------------------
    // Active-low asynchronous reset.
    // rst_n = 0 -> reset
    // rst_n = 1 -> normal operation
    // ------------------------------------------------------------------------
    (* iopad_external_pin *) input rst_n,

    // ------------------------------------------------------------------------
    // Physical SPI interface
    // ------------------------------------------------------------------------
    //
    // spi_ss_n : SPI Slave Select / Chip Select
    //            Active LOW.
    //
    // spi_sck  : SPI clock generated by the external SPI controller.
    //
    // spi_mosi : Controller -> FPGA data.
    //
    // spi_miso : FPGA -> Controller data.
    //
    // spi_miso_en:
    //            Output-enable control for MISO.
    //            HIGH when this SPI target is selected.
    // ------------------------------------------------------------------------
    (* iopad_external_pin *) input  spi_ss_n,
    (* iopad_external_pin *) input  spi_sck,
    (* iopad_external_pin *) input  spi_mosi,
    (* iopad_external_pin *) output spi_miso,
    (* iopad_external_pin *) output spi_miso_en,

    // ------------------------------------------------------------------------
    // LED interface
    // ------------------------------------------------------------------------
    (* iopad_external_pin *) output reg led,
    (* iopad_external_pin *) output led_en
);


    // ========================================================================
    // CONSTANTS / CONFIGURATION
    // ========================================================================

    // SPI configuration
    //
    // CPOL = 0:
    //   SPI clock is LOW when idle.
    //
    // CPHA = 0:
    //   Data is sampled on the rising edge of SCK.
    //
    // LSB = 0:
    //   MSB is transmitted first.
    //
    localparam CPOL  = 1'b0;
    localparam CPHA  = 1'b0;
    localparam WIDTH = 8;
    localparam LSB   = 1'b0;


    // ========================================================================
    // CONSTANT OUTPUT ENABLES
    // ========================================================================
    //
    // The LED output and system clock-enable output are always enabled.
    //
    // These assignments are intentionally simple because this module is
    // intended to be used directly as the FPGA top-level module.
    // ========================================================================

    assign led_en = 1'b1;
    assign clk_en = 1'b1;


    // ========================================================================
    // INTERNAL SPI RX/TX SIGNALS
    // ========================================================================

    // Received SPI byte.
    //
    // This register is updated as MOSI bits are sampled.
    // A complete byte becomes available when rx_valid_pulse is asserted.
    //
    reg [WIDTH-1:0] rx_data_wire;

    // One-clock pulse indicating that a complete SPI byte has been received.
    reg rx_valid_pulse;

    // Data that will be transmitted back to the SPI controller.
    //
    // This implements the simple ECHO functionality:
    //
    //     MCU -> MOSI -> SPI receiver
    //                    |
    //                    v
    //               tx_data_reg
    //                    |
    //                    v
    //               MISO -> MCU
    //
    reg [WIDTH-1:0] tx_data_reg;


    // ========================================================================
    // SPI INPUT SYNCHRONIZATION
    // ========================================================================
    //
    // spi_ss_n, spi_sck and spi_mosi are external signals.
    //
    // They are asynchronous with respect to the 50 MHz system clock.
    // Therefore, the SPI control signals are passed through synchronization
    // registers before being used by the internal logic.
    //
    // Three stages are used here:
    //
    //     external signal
    //          |
    //          v
    //     sync[0]
    //          |
    //          v
    //     sync[1]
    //          |
    //          v
    //     sync[2]
    //
    // sync[1]/sync[2] are then used for edge detection.
    //
    // This reduces the probability of metastability propagating into the
    // functional logic.
    // ========================================================================

    reg [2:0] r_ss_n_sync;
    reg [2:0] r_sck_sync;
    reg [2:0] r_mosi_sync;


    // ------------------------------------------------------------------------
    // SPI Slave Select synchronizer
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // SPI SS is active LOW.
            // Reset to inactive state = HIGH.
            r_ss_n_sync <= 3'b111;
        end
        else begin
            r_ss_n_sync <= {
                r_ss_n_sync[1:0],
                spi_ss_n
            };
        end
    end


    // ------------------------------------------------------------------------
    // SPI clock synchronizer
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            r_sck_sync <= 3'b000;
        end
        else begin
            r_sck_sync <= {
                r_sck_sync[1:0],
                spi_sck
            };
        end
    end


    // ------------------------------------------------------------------------
    // SPI MOSI synchronizer
    // ------------------------------------------------------------------------
    //
    // MOSI is also synchronized because it is generated in the external
    // SPI clock domain.
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            r_mosi_sync <= 3'b000;
        end
        else begin
            r_mosi_sync <= {
                r_mosi_sync[1:0],
                spi_mosi
            };
        end
    end


    // ========================================================================
    // SPI CLOCK EDGE DETECTION
    // ========================================================================
    //
    // After synchronization, the current and previous values of SCK are
    // compared to detect transitions.
    //
    // Rising edge:
    //
    //     previous = 0
    //     current  = 1
    //
    // Falling edge:
    //
    //     previous = 1
    //     current  = 0
    //
    // For SPI Mode 0 (CPOL=0, CPHA=0):
    //
    //     - Rising edge  -> sample MOSI
    //     - Falling edge -> shift/output MISO
    //
    // The expressions below are written generically using CPOL/CPHA.
    // ========================================================================

    wire w_sck_r_edge;
    wire w_sck_f_edge;

    wire w_sck_edge;
    wire w_sck_edge_op;


    // Rising SCK edge after synchronization.
    assign w_sck_r_edge =
            ~r_sck_sync[2] &
             r_sck_sync[1];


    // Falling SCK edge after synchronization.
    assign w_sck_f_edge =
             r_sck_sync[2] &
            ~r_sck_sync[1];


    // Sampling edge.
    //
    // For Mode 0:
    //     CPHA ^ CPOL = 0
    //     therefore w_sck_edge = rising edge.
    assign w_sck_edge =
            (CPHA ^ CPOL) ?
            w_sck_f_edge :
            w_sck_r_edge;


    // Opposite edge.
    //
    // For Mode 0 this is the falling edge.
    // It is used for shifting/transmitting MISO.
    assign w_sck_edge_op =
            (CPHA ^ CPOL) ?
            w_sck_r_edge :
            w_sck_f_edge;


    // ========================================================================
    // SPI BIT COUNTER
    // ========================================================================
    //
    // Counts the number of SPI bits received in the current transaction.
    //
    // For WIDTH = 8:
    //
    //     count = 0 -> first bit
    //     count = 1 -> second bit
    //     ...
    //     count = 7 -> eighth bit
    //
    // After the eighth bit, the counter wraps back to zero.
    //
    // The counter is also cleared whenever SS is inactive.
    // ========================================================================

    reg [$clog2(WIDTH-1):0] r_transmision_count;


    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            r_transmision_count <= 'h0;

        end

        // SPI target is not selected.
        //
        // SS HIGH = inactive.
        else if (r_ss_n_sync[1]) begin

            r_transmision_count <= 'h0;

        end

        // Count one bit on every SPI sampling edge.
        else if (w_sck_edge) begin

            if (r_transmision_count == WIDTH-1) begin

                r_transmision_count <= 'h0;

            end
            else begin

                r_transmision_count <=
                    r_transmision_count + 1'b1;

            end

        end

    end


    // ========================================================================
    // SPI RECEIVE SHIFT REGISTER
    // ========================================================================
    //
    // SPI Mode 0 samples MOSI on the rising edge of SCK.
    //
    // Since LSB = 0, the MSB is received first.
    //
    // Example:
    //
    //     SPI bits:
    //
    //       b7 b6 b5 b4 b3 b2 b1 b0
    //
    // The received bits are shifted into rx_data_wire.
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            rx_data_wire <= 'h0;

        end

        else if (w_sck_edge) begin

            if (LSB) begin

                // LSB-first operation.
                //
                // New bit enters the MSB position.
                rx_data_wire <= {
                    r_mosi_sync[1],
                    rx_data_wire[WIDTH-1:1]
                };

            end

            else begin

                // MSB-first operation.
                //
                // New bit enters the LSB position.
                rx_data_wire <= {
                    rx_data_wire[WIDTH-2:0],
                    r_mosi_sync[1]
                };

            end

        end

    end


    // ========================================================================
    // RX DATA VALID PULSE
    // ========================================================================
    //
    // rx_valid_pulse is asserted for one system-clock cycle when all WIDTH
    // bits of the SPI transaction have been received.
    //
    // For WIDTH = 8:
    //
    //     bit 0 -> count 0
    //     bit 1 -> count 1
    //     ...
    //     bit 7 -> count 7
    //
    // When count == WIDTH-1 and another sampling edge occurs, the byte is
    // complete and rx_valid_pulse is asserted.
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            rx_valid_pulse <= 1'b0;

        end

        // No SPI transaction is active.
        else if (r_ss_n_sync[1]) begin

            rx_valid_pulse <= 1'b0;

        end

        // Clear the valid pulse at the beginning of a new byte.
        else if (r_transmision_count == 0 && w_sck_edge) begin

            rx_valid_pulse <= 1'b0;

        end

        // Eight bits have been received.
        else if (w_sck_edge &&
                 r_transmision_count == WIDTH-1) begin

            rx_valid_pulse <= 1'b1;

        end

        else begin

            rx_valid_pulse <= 1'b0;

        end

    end


    // ========================================================================
    // ECHO DATA REGISTER
    // ========================================================================
    //
    // Whenever a complete byte has been received:
    //
    //     rx_data_wire -> tx_data_reg
    //
    // The SPI transmitter uses tx_data_reg as the data that will be sent
    // back to the external SPI controller.
    //
    // Example:
    //
    //     MCU sends 0x55
    //              |
    //              v
    //           MOSI
    //              |
    //              v
    //       rx_data_wire = 0x55
    //              |
    //              v
    //        tx_data_reg = 0x55
    //              |
    //              v
    //           MISO
    //              |
    //              v
    //          MCU receives
    //
    // NOTE:
    // Because SPI is full-duplex, the byte returned on MISO is shifted
    // during the SPI transaction. Depending on the controller's timing,
    // the echo byte may be observed on the following transaction rather
    // than the same transaction.
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            tx_data_reg <= 8'h00;

        end

        else if (rx_valid_pulse) begin

            tx_data_reg <= rx_data_wire;

        end

    end


    // ========================================================================
    // LED CONTROL
    // ========================================================================
    //
    // Two special SPI commands are defined:
    //
    //     0xAB -> LED ON
    //     0xFF -> LED OFF
    //
    // Any other received value leaves the LED unchanged.
    //
    // This provides a simple hardware-visible indication that the SPI
    // receiver is operating correctly.
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            led <= 1'b0;

        end

        else if (rx_valid_pulse) begin

            if (rx_data_wire == 8'hAB) begin

                // SPI command 0xAB:
                // Turn LED ON.
                led <= 1'b1;

            end

            else if (rx_data_wire == 8'hFF) begin

                // SPI command 0xFF:
                // Turn LED OFF.
                led <= 1'b0;

            end

        end

    end


    // ========================================================================
    // SPI TRANSMIT SHIFT REGISTER
    // ========================================================================
    //
    // r_miso_data contains the byte currently being transmitted to the
    // external SPI controller.
    //
    // In SPI Mode 0:
    //
    //     - Data is prepared before the rising sampling edge.
    //     - MISO is shifted on the falling edge.
    //
    // The first MISO bit must be available before the first rising edge.
    // Therefore the transmit register is loaded when:
    //
    //     SS transitions from inactive -> active
    //
    // The additional condition involving w_sck_edge_op handles loading
    // the next byte when a complete byte boundary is reached.
    // ========================================================================

    reg [WIDTH-1:0] r_miso_data;


    // ------------------------------------------------------------------------
    // Detect the beginning of an SPI transaction.
    //
    // r_ss_n_sync[2] = previous synchronized SS state
    // r_ss_n_sync[1] = current synchronized SS state
    //
    // Therefore:
    //
    //     1 -> 0
    //
    // represents SS becoming active.
    //
    // For CPHA = 0, the transmit register is loaded at this point so that
    // the first MISO bit is already available when the controller samples it.
    // ------------------------------------------------------------------------

    wire o_tx_data_hold;

    assign o_tx_data_hold =
            (~CPHA &
             r_ss_n_sync[2] &
            ~r_ss_n_sync[1])
            |
            ((r_transmision_count == 0) &
             w_sck_edge_op);


    // ------------------------------------------------------------------------
    // MISO transmit shift register
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            r_miso_data <= 'h0;

        end

        // Load the byte that should be transmitted.
        else if (o_tx_data_hold) begin

            r_miso_data <= tx_data_reg;

        end

        // Shift to the next bit after the appropriate SPI edge.
        else if (w_sck_edge_op) begin

            if (LSB) begin

                // LSB-first transmission.
                r_miso_data <= r_miso_data >> 1;

            end

            else begin

                // MSB-first transmission.
                r_miso_data <= r_miso_data << 1;

            end

        end

    end


    // ========================================================================
    // MISO DATA OUTPUT
    // ========================================================================
    //
    // The currently active transmit bit is placed on MISO.
    //
    // MSB-first:
    //
    //     MISO = r_miso_data[WIDTH-1]
    //
    // LSB-first:
    //
    //     MISO = r_miso_data[0]
    // ========================================================================

    assign spi_miso =
            LSB ?
            r_miso_data[0] :
            r_miso_data[WIDTH-1];


    // ========================================================================
    // MISO OUTPUT ENABLE
    // ========================================================================
    //
    // MISO should only actively drive the SPI bus when this device is
    // selected.
    //
    // SS LOW  -> target selected -> MISO enabled
    // SS HIGH -> target deselected -> MISO disabled
    //
    // The signal is exposed as spi_miso_en so that it can be connected to
    // the FPGA I/O output-enable control in the Go Configure / Shrike Lite
    // flow.
    // ========================================================================

    assign spi_miso_en = ~r_ss_n_sync[2];


endmodule