`timescale 1ns/1ps

// ============================================================================
// SPI TARGET + ECHO + LED CONTROL
// FSM-BASED PURE VERILOG IMPLEMENTATION
// ============================================================================
//
// Target platform : Shrike Lite FPGA
// Clock           : 50 MHz
//
// SPI:
//     Mode        : 0
//     CPOL        : 0
//     CPHA        : 0
//     Data        : 8 bits
//     Bit order   : MSB first
//
// FUNCTIONS
// ----------------------------------------------------------------------------
// 1. Receive an 8-bit SPI byte through MOSI.
//
// 2. Decode received commands:
//
//        8'hAB -> LED ON
//        8'hFF -> LED OFF
//        Other -> LED unchanged
//
// 3. Echo the previously received byte through MISO.
//
//    Example:
//
//        SPI transaction 1:
//            Master TX = AB
//            FPGA RX   = AB
//
//        SPI transaction 2:
//            Master TX = 55
//            FPGA RX   = 55
//            Master RX = AB
//
//    This one-transaction delay is intentional because the FPGA cannot
//    know the complete received byte until the eighth rising edge.
//
// 4. MISO is enabled only while SS is LOW.
//
// ============================================================================
//
// IMPORTANT
// ----------------------------------------------------------------------------
// This source is intentionally written in Verilog, NOT SystemVerilog.
//
// No:
//     enum
//     typedef
//     logic
//     always_ff
//     always_comb
//     interface
//     package
//     submodule
//
// ============================================================================


(* top *) module top (

    // ========================================================================
    // SYSTEM INTERFACE
    // ========================================================================

    // 50 MHz system clock.
    (* iopad_external_pin *) input clk,

    // Clock enable output.
    (* iopad_external_pin *) output clk_en,

    // Active-low asynchronous reset.
    (* iopad_external_pin *) input rst_n,


    // ========================================================================
    // SPI INTERFACE
    // ========================================================================

    // SPI slave select.
    //
    // Active LOW:
    //
    //     1 = FPGA not selected
    //     0 = FPGA selected
    //
    (* iopad_external_pin *) input spi_ss_n,

    // SPI clock generated by the external controller.
    (* iopad_external_pin *) input spi_sck,

    // Master -> FPGA.
    (* iopad_external_pin *) input spi_mosi,

    // FPGA -> Master.
    (* iopad_external_pin *) output spi_miso,

    // MISO output enable.
    (* iopad_external_pin *) output spi_miso_en,


    // ========================================================================
    // LED
    // ========================================================================

    (* iopad_external_pin *) output reg led,

    (* iopad_external_pin *) output led_en

);


    // ========================================================================
    // CONSTANT OUTPUTS
    // ========================================================================

    // Clock enable is permanently enabled.
    assign clk_en = 1'b1;

    // LED output enable is permanently enabled.
    assign led_en = 1'b1;


    // ========================================================================
    // SPI INPUT SYNCHRONIZATION
    // ========================================================================
    //
    // The external SPI signals are asynchronous with respect to the
    // 50 MHz FPGA clock.
    //
    // Therefore:
    //
    //     spi_ss_n
    //         |
    //         v
    //       sync0
    //         |
    //         v
    //       sync1
    //         |
    //         v
    //       sync2
    //
    // The same structure is used for SCK and MOSI.
    //
    // sync[1] is used as the functional synchronized signal.
    // sync[2] is used as the previous value for edge detection.
    //
    // ========================================================================

    reg [2:0] r_ss_n_sync;
    reg [2:0] r_sck_sync;
    reg [2:0] r_mosi_sync;


    // ------------------------------------------------------------------------
    // SS synchronizer
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            // SS is inactive HIGH during reset.
            r_ss_n_sync <= 3'b111;

        end
        else begin

            r_ss_n_sync <= {
                r_ss_n_sync[1:0],
                spi_ss_n
            };

        end

    end


    // ------------------------------------------------------------------------
    // SCK synchronizer
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            // SPI Mode 0 has SCK idle LOW.
            r_sck_sync <= 3'b000;

        end
        else begin

            r_sck_sync <= {
                r_sck_sync[1:0],
                spi_sck
            };

        end

    end


    // ------------------------------------------------------------------------
    // MOSI synchronizer
    // ------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            r_mosi_sync <= 3'b000;

        end
        else begin

            r_mosi_sync <= {
                r_mosi_sync[1:0],
                spi_mosi
            };

        end

    end


    // ========================================================================
    // SYNCHRONIZED SPI SIGNALS
    // ========================================================================

    wire w_ss_active;

    // SS LOW means FPGA is selected.
    assign w_ss_active = ~r_ss_n_sync[1];


    // ========================================================================
    // SS EDGE DETECTION
    // ========================================================================
    //
    // SS falling edge:
    //
    //     1 -> 0
    //
    // means a new SPI transaction has started.
    //
    // SS rising edge:
    //
    //     0 -> 1
    //
    // means the SPI transaction has ended.
    //
    // ========================================================================

    wire w_ss_start;
    wire w_ss_end;


    assign w_ss_start =
            r_ss_n_sync[2] &
           ~r_ss_n_sync[1];


    assign w_ss_end =
           ~r_ss_n_sync[2] &
            r_ss_n_sync[1];


    // ========================================================================
    // SPI CLOCK EDGE DETECTION
    // ========================================================================
    //
    // SPI Mode 0:
    //
    //     CPOL = 0
    //     CPHA = 0
    //
    // Therefore:
    //
    //     SCK rising edge:
    //         sample MOSI
    //
    //     SCK falling edge:
    //         change/shift MISO
    //
    // ========================================================================

    wire w_sck_rising;
    wire w_sck_falling;


    // Detect synchronized 0 -> 1 transition.
    assign w_sck_rising =
           ~r_sck_sync[2] &
            r_sck_sync[1];


    // Detect synchronized 1 -> 0 transition.
    assign w_sck_falling =
            r_sck_sync[2] &
           ~r_sck_sync[1];


    // ========================================================================
    // SPI SAMPLE AND SHIFT EDGES
    // ========================================================================
    //
    // For Mode 0:
    //
    //     sample edge = rising edge
    //     shift edge  = falling edge
    //
    // These are wires rather than FSM states because the SPI clock is
    // externally generated.
    //
    // ========================================================================

    wire w_sample_edge;
    wire w_shift_edge;


    assign w_sample_edge = w_sck_rising;

    assign w_shift_edge  = w_sck_falling;


    // ========================================================================
    // FSM STATE DEFINITIONS
    // ========================================================================
    //
    // Three states are used.
    //
    //     ST_IDLE
    //
    //         SPI target is not selected.
    //
    //
    //     ST_RX_ACTIVE
    //
    //         SPI transaction is active.
    //         MOSI is sampled on rising SCK edges.
    //
    //
    //     ST_BYTE_DONE
    //
    //         Eight bits have been received.
    //         The completed byte is decoded.
    //         The received byte is prepared for echo.
    //
    //
    // State diagram:
    //
    //
    //                 SS LOW
    //                    |
    //                    v
    //              +-----------+
    //              |  ST_IDLE  |
    //              +-----------+
    //                    |
    //                    |
    //                    v
    //             +-------------+
    //             | ST_RX_ACTIVE|
    //             +-------------+
    //                |       |
    //        8th bit |       | SS HIGH
    //                |       |
    //                v       v
    //          +------------> IDLE
    //          |
    //          v
    //     +-------------+
    //     | ST_BYTE_DONE|
    //     +-------------+
    //          |
    //          |
    //          v
    //     ST_RX_ACTIVE
    //
    // ========================================================================

    parameter ST_IDLE      = 2'b00;
    parameter ST_RX_ACTIVE = 2'b01;
    parameter ST_BYTE_DONE = 2'b10;


    reg [1:0] state;


    // ========================================================================
    // RECEIVE BIT COUNTER
    // ========================================================================
    //
    // Three bits are sufficient for an 8-bit SPI byte:
    //
    //     0 1 2 3 4 5 6 7
    //
    // Explicit 3'd7 comparisons are used instead of WIDTH-1 to avoid
    // WIDTHEXPAND linter warnings.
    //
    // ========================================================================

    reg [2:0] bit_count;


    // ========================================================================
    // RX SHIFT REGISTER
    // ========================================================================
    //
    // Receives the MOSI data one bit at a time.
    //
    // MSB-first example:
    //
    //     0xAB = 10101011
    //
    // Sampling sequence:
    //
    //     1
    //     0
    //     1
    //     0
    //     1
    //     0
    //     1
    //     1
    //
    // The final shift register becomes:
    //
    //     10101011 = AB
    //
    // ========================================================================

    reg [7:0] rx_data_wire;


    // ========================================================================
    // COMPLETED RX BYTE
    // ========================================================================
    //
    // This register is extremely important.
    //
    // On the eighth sampling edge, rx_data_wire is being updated using a
    // nonblocking assignment.
    //
    // Therefore another always block cannot safely assume that rx_data_wire
    // already contains the new eighth bit during that same clock event.
    //
    // We explicitly calculate and store the COMPLETE byte here.
    //
    // This eliminates the previous:
    //
    //     AA instead of AB
    //
    // problem.
    //
    // ========================================================================

    reg [7:0] rx_completed_byte_reg;


    // ========================================================================
    // CURRENT COMPLETE BYTE CALCULATION
    // ========================================================================
    //
    // At the eighth sampling edge:
    //
    //     rx_data_wire = 10101010
    //
    //     MOSI        = 1
    //
    // Therefore:
    //
    //     w_completed_byte = 10101011
    //
    // ========================================================================

    wire [7:0] w_completed_byte;


    assign w_completed_byte = {
        rx_data_wire[6:0],
        r_mosi_sync[1]
    };


    // ========================================================================
    // RX VALID PULSE
    // ========================================================================
    //
    // One system-clock-cycle indication that a complete byte is available.
    //
    // ========================================================================

    reg rx_valid_pulse;


    // ========================================================================
    // ECHO TRANSMIT DATA
    // ========================================================================
    //
    // This stores the completed byte for transmission during the NEXT SPI
    // transaction.
    //
    // ========================================================================

    reg [7:0] tx_data_reg;


    // ========================================================================
    // MISO SHIFT REGISTER
    // ========================================================================
    //
    // This register controls the actual MISO bits.
    //
    // For MSB-first:
    //
    //     r_miso_data[7] -> first bit
    //     r_miso_data[6] -> second bit
    //     ...
    //     r_miso_data[0] -> last bit
    //
    // ========================================================================

    reg [7:0] r_miso_data;


    // ========================================================================
    // RX SHIFT REGISTER
    // ========================================================================
    //
    // This block samples MOSI on the SPI Mode-0 rising edge.
    //
    // The current MOSI bit is explicitly included in the completed byte.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            rx_data_wire         <= 8'h00;
            rx_completed_byte_reg <= 8'h00;

        end

        else if (!w_ss_active) begin

            // No active transaction.
            //
            // Prepare the receive shift register for a new byte.

            rx_data_wire <= 8'h00;

        end

        else if ((state == ST_RX_ACTIVE) &&
                 w_sample_edge) begin

            // ---------------------------------------------------------------
            // MSB-FIRST RECEIVE
            // ---------------------------------------------------------------
            //
            // Shift existing bits toward MSB and append the new bit at bit 0.
            //
            // Example:
            //
            //     old = 0101010
            //     MOSI = 1
            //
            //     result = 01010101
            //
            // ---------------------------------------------------------------

            rx_data_wire <= {
                rx_data_wire[6:0],
                r_mosi_sync[1]
            };


            // ---------------------------------------------------------------
            // EIGHTH BIT
            // ---------------------------------------------------------------
            //
            // The eighth bit is the final bit of the byte.
            //
            // Store the COMPLETE byte including the current MOSI bit.
            //
            // ---------------------------------------------------------------

            if (bit_count == 3'd7) begin

                rx_completed_byte_reg <= w_completed_byte;

            end

        end

    end


    // ========================================================================
    // RECEIVE BIT COUNTER
    // ========================================================================
    //
    // Counter increments once for every sampled MOSI bit.
    //
    // Sequence:
    //
    //     first bit   -> 0
    //     second bit  -> 1
    //     ...
    //     eighth bit  -> 7
    //
    // After the eighth bit, the counter returns to zero.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            bit_count <= 3'd0;

        end

        else if (!w_ss_active) begin

            // New transaction starts from bit zero.

            bit_count <= 3'd0;

        end

        else if ((state == ST_RX_ACTIVE) &&
                 w_sample_edge) begin

            if (bit_count == 3'd7) begin

                // Eight bits received.

                bit_count <= 3'd0;

            end
            else begin

                bit_count <= bit_count + 3'd1;

            end

        end

    end


    // ========================================================================
    // RX VALID PULSE
    // ========================================================================
    //
    // ST_BYTE_DONE represents a completed byte.
    //
    // rx_valid_pulse is therefore asserted during that state.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            rx_valid_pulse <= 1'b0;

        end
        else begin

            // Default:
            //
            // pulse lasts only one system-clock cycle.

            rx_valid_pulse <= 1'b0;

            if (state == ST_BYTE_DONE) begin

                rx_valid_pulse <= 1'b1;

            end

        end

    end


    // ========================================================================
    // LED COMMAND DECODER
    // ========================================================================
    //
    // Commands:
    //
    //     AB -> ON
    //     FF -> OFF
    //
    // Any other value:
    //
    //     LED retains its current value.
    //
    // The comparison is against rx_completed_byte_reg, NOT rx_data_wire.
    //
    // This is the key fix for the previous LED timing problem.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            led <= 1'b0;

        end

        else if (state == ST_BYTE_DONE) begin

            case (rx_completed_byte_reg)

                8'hAB: begin

                    // Command 0xAB:
                    // Turn LED ON.

                    led <= 1'b1;

                end


                8'hFF: begin

                    // Command 0xFF:
                    // Turn LED OFF.

                    led <= 1'b0;

                end


                default: begin

                    // Any other SPI command does not change LED state.

                    led <= led;

                end

            endcase

        end

    end


    // ========================================================================
    // ECHO DATA REGISTER
    // ========================================================================
    //
    // Once a complete byte has been received:
    //
    //     rx_completed_byte_reg
    //                |
    //                v
    //           tx_data_reg
    //
    // The byte is then available for the NEXT SPI transaction.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            tx_data_reg <= 8'h00;

        end

        else if (state == ST_BYTE_DONE) begin

            tx_data_reg <= rx_completed_byte_reg;

        end

    end


    // ========================================================================
    // MISO TRANSMIT LOGIC
    // ========================================================================
    //
    // SPI Mode 0 requirement:
    //
    //     CPHA = 0
    //
    // Therefore the first MISO bit must already be present BEFORE the first
    // rising edge of SCK.
    //
    // We therefore load r_miso_data when SS becomes active.
    //
    //
    // Example:
    //
    //     tx_data_reg = 10101011
    //
    // At SS assertion:
    //
    //     r_miso_data = 10101011
    //
    // Therefore:
    //
    //     MISO = r_miso_data[7] = 1
    //
    // before the first SCK rising edge.
    //
    // After the falling edge:
    //
    //     r_miso_data = 01010110
    //
    // MISO becomes:
    //
    //     0
    //
    // and so on.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            r_miso_data <= 8'h00;

        end

        else if (w_ss_start) begin

            // ---------------------------------------------------------------
            // NEW SPI TRANSACTION
            // ---------------------------------------------------------------
            //
            // Load the byte captured during the previous transaction.
            //
            // This guarantees the first MISO bit is available before the
            // first rising SCK edge.
            //
            // ---------------------------------------------------------------

            r_miso_data <= tx_data_reg;

        end

        else if (w_shift_edge && w_ss_active) begin

            // ---------------------------------------------------------------
            // MODE-0 TRANSMIT
            // ---------------------------------------------------------------
            //
            // Shift MISO after the falling edge.
            //
            // This gives the next MISO bit time to settle before the next
            // rising edge samples it.
            //
            // ---------------------------------------------------------------

            r_miso_data <= {
                r_miso_data[6:0],
                1'b0
            };

        end

    end


    // ========================================================================
    // MISO OUTPUT
    // ========================================================================
    //
    // MSB-first:
    //
    //     MISO = bit 7 of transmit shift register.
    //
    // ========================================================================

    assign spi_miso = r_miso_data[7];


    // ========================================================================
    // MISO OUTPUT ENABLE
    // ========================================================================
    //
    // SPI target selected:
    //
    //     SS = 0
    //     MISO enabled
    //
    // SPI target not selected:
    //
    //     SS = 1
    //     MISO disabled
    //
    // ========================================================================

    assign spi_miso_en = ~r_ss_n_sync[1];


    // ========================================================================
    // MAIN SPI FSM
    // ========================================================================
    //
    // This is the main control FSM.
    //
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            state <= ST_IDLE;

        end

        else begin

            case (state)

                // ============================================================
                // ST_IDLE
                // ============================================================
                //
                // Waiting for the SPI controller to select the FPGA.
                //
                // SS HIGH:
                //
                //     remain IDLE
                //
                // SS LOW:
                //
                //     begin SPI transaction
                //
                // ============================================================

                ST_IDLE: begin

                    if (w_ss_start) begin

                        state <= ST_RX_ACTIVE;

                    end
                    else begin

                        state <= ST_IDLE;

                    end

                end


                // ============================================================
                // ST_RX_ACTIVE
                // ============================================================
                //
                // SPI transaction is active.
                //
                // Every rising SCK edge samples one MOSI bit.
                //
                // ============================================================

                ST_RX_ACTIVE: begin

                    // --------------------------------------------------------
                    // SPI transaction terminated early.
                    // --------------------------------------------------------

                    if (!w_ss_active) begin

                        state <= ST_IDLE;

                    end


                    // --------------------------------------------------------
                    // EIGHTH BIT RECEIVED.
                    //
                    // The completed byte is now stored in
                    // rx_completed_byte_reg.
                    // --------------------------------------------------------

                    else if (w_sample_edge &&
                             (bit_count == 3'd7)) begin

                        state <= ST_BYTE_DONE;

                    end


                    else begin

                        state <= ST_RX_ACTIVE;

                    end

                end


                // ============================================================
                // ST_BYTE_DONE
                // ============================================================
                //
                // One system-clock state representing a completed byte.
                //
                // During this state:
                //
                //     LED command is decoded.
                //     RX valid pulse is generated.
                //     TX echo register is updated.
                //
                // ============================================================

                ST_BYTE_DONE: begin

                    if (!w_ss_active) begin

                        // SPI controller has released SS.

                        state <= ST_IDLE;

                    end

                    else begin

                        // SS remains LOW.
                        //
                        // Continue receiving another byte in the same
                        // SPI transaction.

                        state <= ST_RX_ACTIVE;

                    end

                end


                // ============================================================
                // DEFAULT
                // ============================================================

                default: begin

                    state <= ST_IDLE;

                end

            endcase

        end

    end


endmodule